import "./globals.css";
import Img from "./public/modipfp3.png";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Modi Jass | Monetize on X</title>
        <meta
          name="description"
          content="Monetize on X I help you build and scale your brand create better content and sign more clients with my 3-step system in 30 days"
        />
        <meta property="og:url" content="https://www.moayadj.com/" />
        <meta property="og:site_name" content="Modi Jass" />
        <meta
          property="og:image"
          content="https://www.moayadj.com/modipfp3.png"
        />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content="Modi Jass" />
        <meta
          name="twitter:description"
          content="Monetize on X I help you build and scale your brand create better content and sign more clients with my 3-step system in 30 days"
        />
      </head>
      <body>{children}</body>
    </html>
  );
}
